/'
2.1.2.10 Unions and Direct Sums of Vector Spaces
Given two vector spaces V and W of the same order, we deﬁne their union,
denoted by V ∪ W, to be the vector space generated by the union of the sets
in the individual vector spaces together with the axpy operation. If V = (V, ◦)
and W = (W, ◦), this is the vector space generated by the set of vectors V ∪W ;
that is,
'/
declare function UnionsAndDirect ( byval v3 as integer = 2,  byval w3 as integer = 1, _
                                   byval u3 as integer = 2,  byval s3 as integer = 1, _ 
                                   byref sets1 as integer ) as integer


type v3

    dim ax9 as integer = 2
    dim yx9 as integer = 4
    dim ux9 as integer = 8

 
end type 

type w3 

    dim ax10 as integer = 2
    dim yx10 as integer = 4
    dim ux10 as integer = 8

end type 


type u3 

    dim ax11 as integer = 2
    dim yx11 as integer = 4
    dim ux11 as integer = 8

end type 

type s3

    dim ax12 as integer = 2
    dim yx12 as integer = 4
    dim ux12 as integer = 8

end type 

type sets1

    dim ax13 as integer = 2
    dim yx13 as integer = 4
    dim ux13 as integer = 8

end type

Print frac(10.625)  '' will print  0.625
Print frac(-10.625) '' will print -0.625

end 


